### PR TITLE
issue/60/main: Added ntakos recipe

### PR DESCRIPTION
**Pull request by mcaibad2**

### CODE REVIEW

**Comment by adityaparab** [comment]
@mcaibad2: would you mind rebasing and fixing the conflicts?

**Comment by mcaibad2** [comment]
I am trying to resolve the conflict using the "Resolve conflicts" button. I made changes and then pressed "Mark as resolved" button. When "Commit merge" is pressed, I get an error message that says "This page is out of date. Start over". 

Pulled changes at my fork and resolved conflicts and tried to make a new PR but i am not allowed to make a new one.

**Comment by Knochenmark** [comment]
@mcaibad2 you shouldn't change formatting. The 2 spaces indentation was intended. Please revert the formatting with 4 spaces and the file changes should also be more readable.

**Comment by Knochenmark** [comment]
Closed due to #70 merged already.

**Pull request closed without merging**
